#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

# BSPWM configuration
#bspc config border_radius        10
bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          40
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

# BSPWM coloring
# Catppuccin
bspc config normal_border_color                "#1E1E2E"
bspc config focused_border_color               "#F28FAD"
# Dracula
#bspc config normal_border_color		"#4d4d4d"
#bspc config focused_border_color		"#bd93f9"

# Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-0 -d 6 7 8 9 10
#bspc monitor HDMI-0 -d 1 2 3 4 5

# Fullscreen applications
#bspc rule -a inkscape state=fullscreen

# Floating applications
bspc rule -a Arandr state=floating
#bspc rule -a rofi state=floating sticky=on

# Tiled applications
#bspc rule -a Gnome-disks state=tiled

#open applications on specific workspaces
#bspc rule -a Firefox desktop='^1' follow=on

### External rules
## Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
## Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
